### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by hfiguiere** [flathub/io.github.orontee.Argos#1]
Build is broken. It sees that the update didn't go through a PR so it didn't get to try the build. Looks like a mismatch tag / commit

**Comment by orontee** [comment]
Sorry, I forgot that PR are required. That said tag and commit are ok from my pov. Can you push force to restore previous commit, aka 6a73baa?

**Comment by hfiguiere** [comment]
maybe it wasn't pushed. Retriggered and it passed.
